package presentacion;

import com.mycompany.chazzboutiquenegocio.dtos.UsuarioDTO;
import com.mycompany.chazzboutiquenegocio.interfacesObjetosNegocio.*;

import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import utils.ScrollBar;

public class FrmMain extends javax.swing.JFrame {

    public IUsuarioNegocio usuarioNegocio;
    public IVentaNegocio ventaNegocio;
    public IVarianteProductoNegocio varianteProductoNegocio;
    public IProductoNegocio productoNegocio;
    public ICategoriaNegocio categoriaNegocio;
    public IProveedorNegocio proveedorNegocio;
    private UsuarioDTO usuarioRegistrado;

    public FrmMain(IUsuarioNegocio usuarioNegocio, IVentaNegocio ventaNegocio,
            IVarianteProductoNegocio varianteProductoNegocio,
            IProductoNegocio productoNegocio, ICategoriaNegocio categoriaNegocio,
            IProveedorNegocio proveedorNegocio, UsuarioDTO usuarioRegistrado) {
        initComponents();
        this.setTitle("ChazzBoutique");
        this.setLocationRelativeTo(null);

        this.usuarioNegocio = usuarioNegocio;
        this.ventaNegocio = ventaNegocio;
        this.varianteProductoNegocio = varianteProductoNegocio;
        this.productoNegocio = productoNegocio;
        this.categoriaNegocio = categoriaNegocio;
        this.proveedorNegocio = proveedorNegocio;
        this.usuarioRegistrado = usuarioRegistrado;

        this.pintarPanelPrincipal(new FrmInicial(this, categoriaNegocio, productoNegocio, proveedorNegocio, varianteProductoNegocio));
    }

    public void pintarPanelPrincipal(JPanel panel) {
        jScrollPane1.setViewportView(panel);
        panel.setPreferredSize(new Dimension(0, panel.getPreferredSize().height));
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }

    public JScrollPane getPanelPrincipal() {
        return jScrollPane1;
    }

    public IVentaNegocio getVentaNegocio() {
        return ventaNegocio;
    }

    public UsuarioDTO getUsuarioRegistrado() {
        return usuarioRegistrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(176, 50, 53));
        jPanel3.setPreferredSize(new java.awt.Dimension(277, 1080));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chazzLogoBlack.png")));

        jPanel4.setBackground(new java.awt.Color(176, 50, 53));
        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(277, 55));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 277, Short.MAX_VALUE));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 55, Short.MAX_VALUE));

        jPanel4.add(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1701, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1078, Short.MAX_VALUE));

        jScrollPane1.setViewportView(jPanel2);
        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        pack();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
